{{- range .Values.processorGroups }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-processor-{{ .eventRange.begin | toString }}
  labels:
    app: message-processor
    group: {{ .name }}
    {{- include "messageprocessor.labels" $ | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-processor
      group: {{ .name }}
      {{- include "messageprocessor.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        app: message-processor
        group: {{ .name }}
        {{- include "messageprocessor.selectorLabels" $ | nindent 8 }}
    spec:
      containers:
      - name: publisher
        image: {{ $.Values.global.image.registry }}/publisher:{{ $.Values.global.image.tag }}
        env:
        - name: ServiceBus__ConnectionString
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.global.servicebus.connectionStringSecret }}
              key: {{ $.Values.global.servicebus.connectionStringKey }}
        - name: Publisher__TopologyType
          value: {{ $.Values.global.topology }}
        - name: Publisher__EventRange__Begin
          value: {{ .eventRange.begin | quote }}
        - name: Publisher__EventRange__End
          value: {{ .eventRange.end | quote }}
        - name: Publisher__BundleTopicName
          value: {{ $.Values.global.bundleTopicName }}
{{- range $index, $subscriber := .subscribers }}
      - name: {{ $subscriber }}
        image: {{ $.Values.global.image.registry }}/subscriber:{{ $.Values.global.image.tag }}
        env:
        - name: ServiceBus__ConnectionString
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.global.servicebus.connectionStringSecret }}
              key: {{ $.Values.global.servicebus.connectionStringKey }}
        - name: Subscriber__TopologyType
          value: {{ $.Values.global.topology }}
        - name: Subscriber__BundleTopicName
          value: {{ $.Values.global.bundleTopicName }}
{{- end }}
{{- end }}
