{{- range .Values.processorGroups }}
{{- $processorGroup := . }}
{{- $name := print $processorGroup.eventRange.begin "" $processorGroup.eventRange.end  -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-processor-{{ $name }}
  labels:
    app: message-processor
    group: {{ .name }}
    {{- include "messageprocessor.labels" $ | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-processor
      group: {{ .name }}
      {{- include "messageprocessor.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        app: message-processor
        group: {{ .name }}
        {{- include "messageprocessor.selectorLabels" $ | nindent 8 }}
    spec:
      containers:
      - name: publisher-{{ $name }}
        image: {{ $.Values.global.image.registry }}/publisher:{{ $.Values.global.image.tag }}
        env:
        - name: ServiceBus__ConnectionString
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.global.servicebus.connectionStringSecret }}
              key: {{ $.Values.global.servicebus.connectionStringKey }}
        - name: Publisher__TopologyType
          value: {{ $.Values.global.topology }}
        - name: Publisher__ThroughputPerMinute
          value: {{ $.Values.global.throughputPerMinute | quote }}          
        - name: Publisher__EventRange__Begin
          value: {{ $processorGroup.eventRange.begin | quote }}
        - name: Publisher__EventRange__End
          value: {{ $processorGroup.eventRange.end | quote }}
        - name: Publisher__BundleTopicName
          value: {{ $.Values.global.bundleTopicName }}
        - name: Publisher__MessageTypesTemplate
          value: {{ $.Values.global.messageTypesTemplate }}         
{{- range $index, $subscriber := .subscribers }}
      - name: {{ $subscriber }}{{ $name }}{{ $index }}
        image: {{ $.Values.global.image.registry }}/subscriber:{{ $.Values.global.image.tag }}
        env:
        - name: ServiceBus__ConnectionString
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.global.servicebus.connectionStringSecret }}
              key: {{ $.Values.global.servicebus.connectionStringKey }}
        - name: Subscriber__TopologyType
          value: {{ $.Values.global.topology }}
        - name: Subscriber__QueueName
          value: {{ $subscriber }}{{ $name }}{{ $index }}
        - name: Subscriber__EventRange__Begin
          value: {{ $processorGroup.eventRange.begin | quote }}
        - name: Subscriber__EventRange__End
          value: {{ $processorGroup.eventRange.end | quote }}
        - name: Subscriber__BundleTopicName
          value: {{ $.Values.global.bundleTopicName }}
        - name: Subscriber__ThroughputPerMinute
          value: {{ $.Values.global.throughputPerMinute | quote }}
        - name: Publisher__MessageTypesTemplate
          value: {{ $.Values.global.messageTypesTemplate }}                      
{{- end }}

---
{{- end }}