# Global settings applied to all pub/sub groups
global:
  topology: "SqlFilter"
  bundleTopicName: "bundle-sql"
  numberOfMessages: 10
  image:
    registry: your-registry
    tag: latest
  servicebus:
    connectionStringSecret: servicebus-secrets
    connectionStringKey: connection-string

# Define multiple publisher/subscriber groups
processorGroups:
  - eventRange:
      begin: 0
      end: 3
    subscribers:
      - subscriber1
      - subscriber2
      - subscriber3
