global:
  topology: "SqlFilter"
  bundleTopicName: "bundle-sqlfilter-dev"
  throughputPerMinute: 100
  image:
    registry: localhost:5000
    tag: latest

processorGroups:
  - eventRange:
      begin: 0
      end: 3
    subscribers:
      - subscriber
      - subscriber
      - subscriber  
  - eventRange:
      begin: 4
      end: 7
    subscribers:
      - subscriber
      - subscriber
      - subscriber     
