global:
  topology: "MassTransit"
  bundleTopicName: "bundle-masstransit-dev"
  publishMultiplier: 1
  image:
    registry: localhost:5000
    tag: latest

processorGroups:
  - eventRange:
      begin: 0
      end: 3
    subscribers:
      - subscriber
      - subscriber
      - subscriber  
  - eventRange:
      begin: 4
      end: 7
    subscribers:
      - subscriber
      - subscriber
      - subscriber     
